services:
  - type: web
    name: fastapi-job-tracker
    env: python
    buildCommand: "pip install -r requirements-prod.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: job-tracker-db
    databaseName: jobtracker
    user: jobtracker_user
